#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <message_commit>"
    exit 1
fi

git add .

git status

read -p "Do you really want to add this changes ? (y/n) " confirm
if [ "$confirm" != "y" ]; then
    echo "Push cancelled."
    exit 1
fi

git commit -m "$1"

git push origin main

echo "Push done."
