#!/usr/bin/env python3

import os
import re
from colorama import Fore, Style

def search_banned_functions(directory):
    banned_functions = input("Enter the names of banned functions (separated by spaces): ").split()

    for parent_folder, subfolders, files in os.walk(directory):
        for file in files:
            
            if not file.endswith(".c"):
                continue
            
            file_path = os.path.join(parent_folder, file)

            if not os.path.exists(file_path) or os.path.islink(file_path):
                continue

            with open(file_path, 'r') as file:
                content = file.read()
                banned_function_found = False
                for banned_function in banned_functions:
                    pattern = re.compile(r'\b' + re.escape(banned_function) + r'\b')
                    if pattern.search(content):
                        print(Fore.RED + f"File: {file_path}\nBanned function found: {banned_function}\n" + Style.RESET_ALL)
                        banned_function_found = True
                        break
                
                if not banned_function_found:
                    print(Fore.GREEN + f"File: {file_path}\nNo banned functions found.\n" + Style.RESET_ALL)

if __name__ == "__main__":
    directory_to_explore = input("Enter the path of the directory to explore: ")
    search_banned_functions(directory_to_explore)
